apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapi-deployment
  labels:
    app: demoapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapi
  template:
    metadata:
      labels:
        app: demoapi
    spec:
      containers:
      - name: demoapi
        image: ACR_NAME_PLACEHOLDER/demoapi:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
          
livenessProbe:
  httpGet:
    path: /weatherforecast
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /weatherforecast
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
