name: Build and Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

#JOB 1 : Terraform - Provision Infrastructure
jobs:
  terraform:
    name: Terraform - Provision Infrastructure
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ secrets.TF_RESOURCE_GROUP }}" \
          -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" \
          -backend-config="key=demoapi.terraform.tfstate" \
          -backend-config="use_azuread_auth=true"
      
      - name : Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="resource_group_name=${{secrets.AKS_RESOURCE_GROUP}}" \
            -var="aks_cluster_name=${{secrets.AKS_CLUSTER_NAME}}" \
            -var="location=${{secrets.AKS_LOCATION}}" \
            -var="acr_name=${{secrets.ACR_NAME}}"
            -var="environment=dev"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="resource_group_name=${{secrets.AKS_RESOURCE_GROUP}}" \
            -var="aks_cluster_name=${{secrets.AKS_CLUSTER_NAME}}" \
            -var="location=${{secrets.AKS_LOCATION}}" \
            -var="acr_name=${{secrets.ACR_NAME}}" \
            -var="environment=dev"

#JOB 2 - Build and Publish
  build-and-publish:
    runs-on: ubuntu-latest
    needs: terraform
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}} 
      
      - name: Build and Push Image
        run: |
         az acr login --name ${{secrets.ACR_NAME}}
         docker buildx build \
         --platform linux/amd64 \
         -f docker/DemoApi.Dockerfile \
         -t ${{secrets.ACR_NAME}}.azurecr.io/demoapi:${{github.sha}} \
         --push .
         
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{secrets.AKS_RESOURCE_GROUP}}
          cluster-name: ${{secrets.AKS_CLUSTER_NAME}}

      - name: Update image in manifest
        run: |
          sed -i 's|ACR_NAME_PLACEHOLDER|${{ secrets.ACR_NAME }}.azurecr.io|g' k8/deployment.yaml

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8/deployment.yaml
            k8/service.yaml
            k8/hpa.yaml
          images: |
            ${{ secrets.ACR_NAME }}.azurecr.io/demoapi:${{ github.sha }}
