name: Build and Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: dev 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}} 
      
      - name: Build and Push Image
        run: |
         az acr login --name ${{secrets.ACR_NAME}}
         docker buildx build \
         --platform linux/amd64 \
         -f docker/DemoApi.Dockerfile \
         -t ${{secrets.ACR_NAME}}.azurecr.io/demoapi:${{github.sha}} \
         --push .
         
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{secrets.AKS_RESOURCE_GROUP}}
          cluster-name: ${{secrets.AKS_CLUSTER_NAME}}

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8/deployment.yaml
            k8/service.yaml
          images: |
            ${{secrets.ACR_NAME}}.azurecr.io/demoapi:${{github.sha}}

