name: Infrastructure — Terragrunt

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'        # only runs when infra files change
  workflow_dispatch:      # allow manual trigger

concurrency:
  group: 'terragrunt-${{ github.ref }}'  # concurrency group based on branch name
  cancel-in-progress: false  # do not cancel in-progress runs

env:
    TERRAGRUNT_VERSION: 0.63.6
    TERRAFORM_VERSION: 1.7.0

jobs:
  dev:
    name: Terragrunt - Dev
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./infra/environments/dev   # ← fixed path
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
          
      - name: Debug repo root
        run: ls -R $GITHUB_WORKSPACE

      - name: Setup Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version

      - name : Terragrunt Validate
        run: terragrunt init --terragrunt-non-interactive

      - name: Terragrunt Plan
        run: terragrunt plan --terragrunt-non-interactive

      - name: Terragrunt Apply
        run: terragrunt apply -auto-approve -input=false -lock-timeout=10m

